### ISSUE TITLE
CI tests fail due to precompilation errors in OrdinaryDiffEq.jl et co

### ISSUE THREAD

**Issue by andreasvarga** [SciML/OrdinaryDiffEq.jl#2887]
I recently updated the [PeriodicMatrixEquations.jl](https://github.com/andreasvarga/PeriodicMatrixEquations.jl) package and tried to perform the CI tests with the recent version v1.12 of Julia. The tests fail because of several precompilation errors (see [here](https://github.com/andreasvarga/PeriodicMatrixEquations.jl/actions/runs/18464838083/job/52604238948)) occured in  `OrdinaryDiffEq.jl` and related packages. I would appreciate any advice how to overcome these errors.

**Comment by Ickaser** [comment]
It isn't loading the most up-to-date versions of SciML packages in your CI, and I suspect that the breakage on 1.12 has likely been fixed in more recent versions. I tried downloading PeriodicMatrixEquations.jl and instantiating to see where your compat bounds are coming from, and the compat bounds it is working with are nontrivial, but my best guess is that it stems from holding Symbolics back to version 4 or 5 when v6 has been out for a while. 

Specifically, using an old Symbolics is holding back DataStructures to 0.18 (more current is 0.19), as well as ForwardDiff to 0.10 (more current is 1.2). Both of those compat bounds are holding back other packages, so you are missing the fixes that make everything work on 1.12.

The compat bound you want to bump is https://github.com/andreasvarga/PeriodicMatrixEquations.jl/blob/fae5d9bdd536af0e9e49faec9ee6c79e98d524e7/Project.toml#L39, and

You can see this yourself with the following in a clean Project.toml:

```julia
] add https://github.com/andreasvarga/PeriodicMatrixEquations.jl.git
] st --outdated -m
```
When I did so just now, I got:
```
⌅ [e2ed5e7c] Bijections v0.1.10 (<v0.2.2): SymbolicUtils, Symbolics
⌃ [70df07ce] BracketingNonlinearSolve v1.3.0 (<v1.5.0)
⌅ [187b0558] ConstructionBase v1.5.6 (<v1.6.0): SymbolicUtils
⌅ [864edb3b] DataStructures v0.18.22 (<v0.19.1): DiffEqBase, MultivariatePolynomials, OrdinaryDiffEq, OrdinaryDiffEqCore, SparseDiffTools, SymbolicUtils, Symbolics
⌃ [2b5f629d] DiffEqBase v6.174.0 (<v6.190.2)
⌅ [7c1d4256] DynamicPolynomials v0.5.7 (<v0.6.4): SymbolicUtils, Symbolics
⌅ [f6369f11] ForwardDiff v0.10.39 (<v1.2.1): OrdinaryDiffEqDifferentiation, OrdinaryDiffEqNonlinearSolve, OrdinaryDiffEqRosenbrock, Symbolics
⌅ [a98d9a8b] Interpolations v0.15.1 (<v0.16.2): PeriodicMatrices
⌅ [984bce1d] LambertW v0.4.6 (<v1.0.0): Symbolics
⌃ [7ed4a6bd] LinearSolve v3.26.0 (<v3.44.0)
⌃ [102ac46a] MultivariatePolynomials v0.5.9 (<v0.5.13)
⌃ [8913a72c] NonlinearSolve v4.10.0 (<v4.12.0)
⌅ [be0214bd] NonlinearSolveBase v1.8.0 (<v2.0.0): BracketingNonlinearSolve, NonlinearSolve, NonlinearSolveFirstOrder, NonlinearSolveQuasiNewton, NonlinearSolveSpectralMethods, SimpleNonlinearSolve
⌃ [5959db7a] NonlinearSolveFirstOrder v1.7.0 (<v1.9.0)
⌃ [9a2c21bd] NonlinearSolveQuasiNewton v1.5.0 (<v1.10.0)
⌃ [26075421] NonlinearSolveSpectralMethods v1.3.0 (<v1.5.0)
⌃ [1dea7af3] OrdinaryDiffEq v6.101.0 (<v6.102.1)
⌃ [89bda076] OrdinaryDiffEqAdamsBashforthMoulton v1.3.0 (<v1.5.0)
⌃ [6ad6398a] OrdinaryDiffEqBDF v1.3.0 (<v1.10.1)
⌃ [bbf590c4] OrdinaryDiffEqCore v1.26.2 (<v1.36.0)
⌃ [50262376] OrdinaryDiffEqDefault v1.6.0 (<v1.8.0)
⌃ [4302a76b] OrdinaryDiffEqDifferentiation v1.4.0 (<v1.16.1)
⌃ [9286f039] OrdinaryDiffEqExplicitRK v1.2.0 (<v1.4.0)
⌃ [e0540318] OrdinaryDiffEqExponentialRK v1.6.0 (<v1.8.0)
⌃ [becaefa8] OrdinaryDiffEqExtrapolation v1.6.0 (<v1.9.0)
⌃ [5960d6e9] OrdinaryDiffEqFIRK v1.9.0 (<v1.16.0)
⌃ [101fe9f7] OrdinaryDiffEqFeagin v1.2.0 (<v1.4.0)
⌃ [d3585ca7] OrdinaryDiffEqFunctionMap v1.3.0 (<v1.5.0)
⌃ [d28bc4f8] OrdinaryDiffEqHighOrderRK v1.3.0 (<v1.5.0)
⌃ [9f002381] OrdinaryDiffEqIMEXMultistep v1.5.0 (<v1.7.0)
⌃ [521117fe] OrdinaryDiffEqLinear v1.4.0 (<v1.6.0)
⌃ [1344f307] OrdinaryDiffEqLowOrderRK v1.4.0 (<v1.6.0)
⌃ [b0944070] OrdinaryDiffEqLowStorageRK v1.4.0 (<v1.7.0)
⌃ [127b3ac7] OrdinaryDiffEqNonlinearSolve v1.5.0 (<v1.15.0)
⌃ [c9986a66] OrdinaryDiffEqNordsieck v1.2.0 (<v1.4.0)
⌃ [5dd0a6cf] OrdinaryDiffEqPDIRK v1.4.0 (<v1.6.0)
⌃ [5b33eab2] OrdinaryDiffEqPRK v1.2.0 (<v1.4.0)
⌃ [04162be5] OrdinaryDiffEqQPRK v1.2.0 (<v1.4.0)
⌃ [af6ede74] OrdinaryDiffEqRKN v1.3.0 (<v1.5.0)
⌃ [43230ef6] OrdinaryDiffEqRosenbrock v1.8.0 (<v1.18.1)
⌃ [2d112036] OrdinaryDiffEqSDIRK v1.5.0 (<v1.7.0)
⌃ [669c94d9] OrdinaryDiffEqSSPRK v1.4.0 (<v1.7.0)
⌃ [e3e12d00] OrdinaryDiffEqStabilizedIRK v1.4.0 (<v1.6.0)
⌃ [358294b1] OrdinaryDiffEqStabilizedRK v1.3.0 (<v1.4.0)
⌃ [fa646aed] OrdinaryDiffEqSymplecticRK v1.5.0 (<v1.7.0)
⌃ [b1df2697] OrdinaryDiffEqTsit5 v1.3.0 (<v1.5.0)
⌃ [79d7bb75] OrdinaryDiffEqVerner v1.4.0 (<v1.6.0)
⌃ [0bca4576] SciMLBase v2.87.0 (<v2.120.0)
⌃ [19f34311] SciMLJacobianOperators v0.1.5 (<v0.1.11)
⌅ [c0aeaf25] SciMLOperators v0.3.13 (<v1.9.0): NonlinearSolveBase, NonlinearSolveQuasiNewton, OrdinaryDiffEqFIRK, OrdinaryDiffEqNonlinearSolve, SciMLBase, SciMLJacobianOperators, SparseDiffTools
⌃ [727e6d20] SimpleNonlinearSolve v2.7.0 (<v2.9.0)
⌃ [19f23fe9] SymbolicLimits v0.2.1 (<v0.2.4)
⌅ [d1185830] SymbolicUtils v2.1.3 (<v4.0.0): SymbolicLimits, Symbolics
⌃ [0c5d862f] Symbolics v5.36.0 (<v6.55.0)
⌅ [8ea1fca8] TermInterface v0.4.1 (<v2.0.0): SymbolicUtils, Symbolics
```

**Comment by andreasvarga** [comment]
Thanks. I fixed the compat issue.
